from models.bsuser import *
from models.bsadmin import *
from models.contest import *
from models.contestproblem import *
from models.problem import *
from models.problemtag import *
from models.record import *
from models.registration import *
from models.tag import *
